In [1]:
from scipy import stats
import numpy as np

In [2]:
# 20、15、26、32、18、28、35、14、26、22、17
# 60 is the maxium score.

pass within one sigma, 84% pass, only 16% don't pass

In [3]:
scores = [20, 15, 26, 32, 18, 28, 35, 14, 26, 22, 17]

In [4]:
score_np = np.array([20, 15, 26, 32, 18, 28, 35, 14, 26, 22, 17])

In [6]:
print(type(scores))
print(type(score_np))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
stats.zscore(scores)

array([-0.45226702, -1.20604538,  0.45226702,  1.35680105, -0.75377836,
        0.75377836,  1.80906807, -1.35680105,  0.45226702, -0.15075567,
       -0.90453403])

In [8]:
stats.zscore(score_np)

array([-0.45226702, -1.20604538,  0.45226702,  1.35680105, -0.75377836,
        0.75377836,  1.80906807, -1.35680105,  0.45226702, -0.15075567,
       -0.90453403])

In [9]:
stats.zscore(scores) <= -1 

array([False,  True, False, False, False, False, False,  True, False,
       False, False])

In [13]:
list(enumerate(scores,1))

[(1, 20),
 (2, 15),
 (3, 26),
 (4, 32),
 (5, 18),
 (6, 28),
 (7, 35),
 (8, 14),
 (9, 26),
 (10, 22),
 (11, 17)]

In [17]:
list(enumerate((stats.zscore(scores) <= -1),1))

[(1, False),
 (2, True),
 (3, False),
 (4, False),
 (5, False),
 (6, False),
 (7, False),
 (8, True),
 (9, False),
 (10, False),
 (11, False)]

In [ ]:
# So, if it's 1 sigma away not pass the test, no.2 and no.8 are out.

If we want over 60% score to pass the exam, then...

In [ ]:
#  from the z-score table, the extra 10% is 0.26, that means, if we only want 60% of them to pass
#  the passing score should be:

In [18]:
23+(0.23*6.6)

24.518

In [25]:
scores >= 24.518

TypeError: '>=' not supported between instances of 'list' and 'float'

In [24]:
score_np >= 24.518

array([False, False,  True,  True, False,  True,  True, False,  True,
       False, False])

In [27]:
stats.zscore(score_np)>= 0.26

array([False, False,  True,  True, False,  True,  True, False,  True,
       False, False])

In [ ]:
# 从上例中可以看出，