In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from sklearn.datasets import load_iris

#### 2 matrix multiply

In [2]:
x = [(90,80),(80,70),(70,60),(100,100)]
y = [[0.7],[0.3]]

In [3]:
np.dot(x,y)

array([[ 87.],
       [ 77.],
       [ 67.],
       [100.]])

In [4]:
np.array(x)

array([[ 90,  80],
       [ 80,  70],
       [ 70,  60],
       [100, 100]])

In [5]:
from sklearn.linear_model import LinearRegression

In [6]:
from sklearn.linear_model import SGDRegressor

#### The transformation of a vector in different coordinate system

In [7]:
#cs1
basis_vector1=np.array([[1,0],[0,1]])
vector_1= np.array([3,2])

In [8]:
basis_vector1

array([[1, 0],
       [0, 1]])

In [9]:
vector_1

array([3, 2])

In [10]:
inverse = np.array([[0,1],[1,0]])

In [11]:
inverse

array([[0, 1],
       [1, 0]])

In [12]:
np.dot(vector_1, inverse)

array([2, 3])

In [13]:
basis_vector2=np.array([[2,1],[-1,1]])

In [14]:
np.dot(vector1,basis_vector2)

NameError: name 'vector1' is not defined

In [ ]:
vector_2 = np.array([-1,2])

In [ ]:
print('transform vector_2 into cs1:',np.dot(vector_2,basis_vector2))

In [15]:
np.dot(np.array([1,0]),np.array([0,1]))

0

np.where()

In [5]:
single = np.array([24, 26, 35, 32, 38, 35, 31, 43, 40, 42, 39, 48, 37, 27, 33, 33, 34,
                   37, 33, 26, 30, 30, 30, 31, 33, 35, 43, 30, 35, 26, 23, 27, 54, 35,
                   29, 28, 37, 33, 34, 32, 29, 43, 29, 36, 36, 34, 39, 33, 30, 32, 23,
                   30, 31, 38, 35, 22, 59, 20, 45, 33, 35, 33, 23, 58, 33, 30, 38, 28,
                   50, 31, 38, 42, 41, 33, 29, 29, 31, 30, 28, 27, 29, 38, 36, 56, 36,
                   31, 30, 29, 25, 41, 47, 34, 38, 50, 23, 28, 35, 32, 36, 28, 39, 33,
                   25, 36, 27, 30, 29, 42, 43, 20, 26, 53, 41, 27, 31, 33, 38, 37, 31,
                   28, 25, 47, 38, 41, 26, 26, 25, 32, 32, 23, 31, 51, 49, 32, 48, 44,
                   30, 31, 34, 37, 31, 32, 24, 38, 38, 39, 29, 25, 29, 31, 24, 35, 28,
                   24, 24, 35, 36, 21, 56, 54, 28, 32, 27, 30, 31, 31, 27, 32, 30, 29,
                   27, 26, 36, 27, 32, 32, 38, 41, 33, 33, 26, 29, 27, 42, 35, 32, 35,
                   43, 32, 22, 32, 37, 30, 39, 28, 33, 25, 34, 39, 31])

In [6]:
bool
(single > 30)*1

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1])