In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

#### 2 matrix multiply

In [3]:
x = [(90,80),(80,70),(70,60),(100,100)]
y = [[0.7],[0.3]]

In [4]:
np.dot(x,y)

array([[ 87.],
       [ 77.],
       [ 67.],
       [100.]])

In [6]:
np.array(x)

array([[ 90,  80],
       [ 80,  70],
       [ 70,  60],
       [100, 100]])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
from sklearn.linear_model import SGDRegressor

#### The transformation of a vector in different coordinate system

In [17]:
#cs1
basis_vector1=np.array([[1,0],[0,1]])
vector_1= np.array([3,2])

In [18]:
basis_vector1

array([[1, 0],
       [0, 1]])

In [19]:
vector_1

array([3, 2])

In [5]:
inverse = np.array([[0,1],[1,0]])

In [6]:
inverse

array([[0, 1],
       [1, 0]])

In [20]:
np.dot(vector_1, inverse)

array([2, 3])

In [10]:
basis_vector2=np.array([[2,1],[-1,1]])

In [11]:
np.dot(vector1,basis_vector2)

array([4, 5])

In [14]:
vector_2 = np.array([-1,2])

In [37]:
print('transform vector_2 into cs1:',np.dot(vector_2,basis_vector2))

transform vector_2 into cs1: [-4  1]


In [38]:
np.dot(np.array([1,0]),np.array([0,1]))

0