In [116]:
import sklearn 
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import jieba
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import h5py
import numpy as np

In [6]:
def datasets_demo():
#   获取数据集
    iris = load_iris()
#   print('鸢尾花数据集: \n', iris)
    print('查看数据描述: \n', iris['DESCR'])
    print('查看属性名字: \n', iris.feature_names)
    
#   数据集划分
    x_train, x_test, y_train, y_test= train_test_split(iris.data,iris.target,test_size=0.2, random_state=22 )
    print('查看训练集: \n', x_train, x_train.shape )
    
    return None

In [31]:
def dict_demo():
    #字典特征抽取
    data = [{'city':'北京','temperature':100},{'city':'上海', 'temperature':60},{'city':'深圳', 'temperature':30}]
#     1. 实例化的一个转换器
    transfer = DictVectorizer(sparse=True) 
#     2.调动fit_transform()
    data_new = transfer.fit_transform(data)
    print('data_new + sparse=True(显示二维数组的结果): \n',data_new)
    print('data_new + toarray : \n', type(data_new),'\n', data_new.toarray())
    print('特征名 :\n',transfer.get_feature_names())
    return None

In [51]:
def count_demo():
    #文本特征抽取
    data = ['life is short, i like like python','life is too long, i dislike python']
    # 实例化一个转化器类
    transfer = CountVectorizer(stop_words=['is','too'])
#     调用fit_transform
    data_new=transfer.fit_transform(data)
    print('特征名 :\n',transfer.get_feature_names())
    print('data_new: \n', data_new)
    print('data_new + toarray 查看二维数组的结果: \n', data_new.toarray())
    
    return None

In [52]:
def count_chinese_demo():
    #文本特征抽取 
    data = ['我 爱 北京 天安门，','天安门 上 太阳 升。']
#     如果不空格，整句将被视为一个单词来处理
#     data = ['我爱北京天安门，','天安门上太阳升。']
    # 实例化一个转化器类
    transfer = CountVectorizer()
#     调用fit_transform
    data_new=transfer.fit_transform(data)
    print('特征名 :\n',transfer.get_feature_names())
    print('data_new: \n', data_new)
    print('data_new + toarray 查看二维数组的结果: \n', data_new.toarray())
    
    return None

In [100]:
def cut_word(text):
#     进行中文分词：‘我爱北京天安门’ ---‘我 爱 北京 天安门’
    a =  list(jieba.cut(text))
#     如果直接打印jieba.cut(text)是看不到结果的，一定熬list强转 ，加上"".join()让list变成一个str
    print(a)
    return None

In [101]:
def count_chinese_demo2():
#     中文文本特征抽取，自动分词
    data=['一种还是一种今天很残酷，明天更残酷，后天很美好，但绝大部分是死在明天晚上，所以每个人不要放弃今天',
         '我们看到的从很远星系来的光是在几百万年前发出的，这样当我们看到宇宙时，我们是在看它的过去',
         '如果只用一种方式了解某样事物，你就不会真正了解它。了解事物真正含义的秘密取决于如何将其与我们所了解的事物相联系。']
    

    return None

In [110]:
def tfidf_demo():
#     用tf-idf做文本特征抽取
    data = ['一种还是一种今天很残酷，明天更残酷，后天很美好，但绝大部分是死在明天晚上，所以每个人不要放弃今天',
         '我们看到的从很远星系来的光是在几百万年前发出的，这样当我们看到宇宙时，我们是在看它的过去',
         '如果只用一种方式了解某样事物，你就不会真正了解它。了解事物真正含义的秘密取决于如何将其与我们所了解的事物相联系。']
    data_new = []
    for sent in data:
        data_new.append(cut_word(sent))
#     如果不空格，整句将被视为一个单词来处理
#     data = ['我爱北京天安门，','天安门上太阳升。']
    # 实例化一个转化器类
    transfer = TfidfVectorizer()
#     调用fit_transform
    data_final=transfer.fit_transform(data_new)
    print('特征名 :\n',transfer.get_feature_names())
    print('data_new: \n', data_fianl)
    print('data_new + toarray 查看二维数组的结果: \n', data_final.toarray())
    
    return None

In [125]:
df = pd.read_csv('dating.txt', header = None, sep='\t')

df[3] = [3 if i=='largeDoses' else 2 if i=='smallDoses' else 1 for i in df[3]]

dating=df

dating.columns = ['milage','liters','consumtime','target']

In [142]:
def minmax_demo():
#     归一化
#     获取数据
    data=dating
    data=data.iloc[:,:3]
#     实例化一个转换器
    transfer = MinMaxScaler()
#     调用fit_transform
    data_new = transfer.fit_transform(data)
    print('data_new : \n', data_new)
    return None

In [147]:
def stand_demo():
#     标准化
#     获取数据
    data=dating
    data=data.iloc[:,:3]
#     实例化一个转换器
    transfer = StandardScaler()
#     调用fit_transform
    data_new = transfer.fit_transform(data)
    print('data_new : \n', data_new)
    return None

In [148]:
if __name__ == "__main__":
#     代码1.sklearn数据集使用
#     datasets_demo()
#     代码2.字典特征抽取
#     dict_demo()
#     代码3.文本的特征抽取
#     count_demo()
#     代码3.中文文本
#     count_chinese_demo()
#   代码4.中文文本，自动分词
#     count_chinese_demo2()
#     代码5.jieba分词测试,不成功，原因是分词在"".join()后，str没有空格
#     cut_word('我爱北京天安门') 
#     代码6.tiidf关键词提取
#     tfidf_demo()
#     代码7.归一化
#     minmax_demo()
#     代码8.标准化
    stand_demo()

data_new : 
 [[ 0.33193158  0.41660188  0.24523407]
 [-0.87247784  0.13992897  1.69385734]
 [-0.34554872 -1.20667094 -0.05422437]
 ...
 [-0.32171752  0.96431572  0.06952649]
 [ 0.65959911  0.60699509 -0.20931587]
 [ 0.46120328  0.31183342  1.00680598]]


/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/anaconda3/lib/python3.7/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [215]:
# insstcart demo _ PCA
# 1.获取数据，2.合并表，3.找到user_id和aisels之间的关系
from sklearn.decomposition import PCA
# 获取数据
aisles = pd.read_csv('/Users/paxton615/Downloads/DATABASE/instacart-market-basket-analysis/aisles.csv')
order_products__prior = pd.read_csv('/Users/paxton615/Downloads/DATABASE/instacart-market-basket-analysis/order_products__prior.csv')
orders = pd.read_csv('/Users/paxton615/Downloads/DATABASE/instacart-market-basket-analysis/orders.csv')
departments = pd.read_csv('/Users/paxton615/Downloads/DATABASE/instacart-market-basket-analysis/departments.csv')
# order_products__train = pd.read_csv('/Users/paxton615/Downloads/DATABASE/instacart-market-basket-analysis/order_products__train.csv')
products = pd.read_csv('/Users/paxton615/Downloads/DATABASE/instacart-market-basket-analysis/products.csv')
# 查看表头
# print(aisles.columns, '\n','\n', orders.columns,'\n','\n', departments.columns, '\n','\n',products.columns)
# 合并表
tab1 =pd.merge( pd.merge(aisles, products, on='aisle_id'),order_products__prior,on='product_id')
tab2 = pd.merge(tab1, orders, on='order_id')
#找到user_id和aisles之间的关系
table = pd.crosstab(tab2['user_id'],tab2['aisle'])
# 截取table的一部分做测试
data = table[:10000]
# 1.实例化一个转换器类
transfer = PCA(n_components=0.95)
# 2.调用fit_transform
data_new = transfer.fit_transform(data)
# 查看PCA结果
print(table.shape)
print(data_new.shape) # 保留了95的信息，但维数从134变成了42

(206209, 134)
(10000, 42)


In [214]:
with h5py.File('/Users/paxton615/Downloads/facebook-v-results/top_submissions.h5','r') as hdf:
    ls = list (hdf.keys())
    print('list of datasets in this file: \n',ls)
    data = hdf.get('Solution')
    Solution = np.array(data)
    print('shape of dataset: \n', dataset1.shape)

OSError: Unable to open file (unable to open file: name = '/Users/paxton615/Downloads/facebook-v-results/top_submissions.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)