<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Classification and KNN with NHL data


---

Below you will practice KNN classification on a dataset of NHL statistics.

You will be predicting the `Rank` of a team from predictor variables of your choice.

In [80]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

sns.set(font_scale=1.5)
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [81]:
# web location:
#csv_file = 'https://raw.githubusercontent.com/josephofiowa/GA-DSI/master/NHL_Data_GA.csv'
csv_file = './datasets/NHL_Data_GA.csv'
df = pd.read_csv(csv_file)

In [82]:
df.head()
df=pd.DataFrame(df)

In [83]:
df.columns

Index(['Team', 'PTS', 'Rank', 'TOI', 'GF', 'GA', 'GF60', 'GA60', 'GF%', 'SF',
       'SA', 'SF60', 'SA60', 'SF%', 'FF', 'FA', 'FF60', 'FA60', 'FF%', 'CF',
       'CA', 'CF60', 'CA60', 'CF%', 'Sh%', 'Sv%', 'PDO', 'PIM'],
      dtype='object')

### 1. Load the NHL data

In [84]:
# A:
#df.dtypes  # find out how I seperate Dates, from yesterday's project
df.head()

Team  PTS  Rank         TOI   GF  GA  GF60  GA60   GF%    SF  ...  \
0  Washington10  121     1  2001:52:00  115  73  3.45  2.19  61.2  1112  ...   
1   Vancouver11  117     1  2056:14:00   94  72  2.74  2.10  56.6  1143  ...   
2    San Jose10  113     1  1929:54:00   90  68  2.80  2.11  57.0  1065  ...   
3     Chicago10  112     1  2020:23:00  104  83  3.09  2.46  55.6  1186  ...   
4   Vancouver12  111     1  2052:02:00   86  74  2.51  2.16  53.8  1078  ...   

    FF%    CF    CA  CF60  CA60   CF%    Sh%    Sv%   PDO   PIM  
0  51.3  2138  1935  64.1  58.0  52.5  10.34  93.03  1034  1269  
1  53.1  2144  1870  62.6  54.6  53.4   8.22  93.16  1014   985  
2  50.9  1985  1876  61.7  58.3  51.4   8.45  93.46  1019  1195  
3  58.1  2093  1572  62.2  46.7  57.1   8.77  90.44   992   966  
4  51.0  2085  1880  61.0  55.0  52.6   7.98  93.36  1013  1049  

[5 rows x 28 columns]

### 2. Perform any required data cleaning. Do some EDA.

In [86]:
#movies_rev['year']= movies_rev.release_date.apply(lambda x: float((str(x).split('-'))[0]))
#movies_rev['month']=movies_rev.release_date.apply(lambda x: float((str(x).split('-'))[1]))
#movies_rev.head(1)
df.TOI.appply(lambda x:float((str(x).split(":"))[0]))

AttributeError: 'Series' object has no attribute 'appply'

### 3. Set up the `Rank` variable as your target. How many classes are there?

In [29]:
df.columns

Index(['Team', 'PTS', 'Rank', 'TOI', 'GF', 'GA', 'GF60', 'GA60', 'GF%', 'SF',
       'SA', 'SF60', 'SA60', 'SF%', 'FF', 'FA', 'FF60', 'FA60', 'FF%', 'CF',
       'CA', 'CF60', 'CA60', 'CF%', 'Sh%', 'Sv%', 'PDO', 'PIM'],
      dtype='object')

In [39]:
X = df[["GA","GF","SF%","GA"]]
y = df["Rank"]

In [40]:
y.value_counts()


3    31
2    30
1    29
Name: Rank, dtype: int64

In [41]:
X.columns


Index(['GA', 'GF', 'SF%', 'GA'], dtype='object')

### 4. What is the baseline accuracy?

In [43]:
baseline = np.mean(y)
baseline

2.022222222222222

In [48]:
baseline = 1. - np.mean(y)
baseline

-1.0222222222222221

In [44]:
print(list(y))


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [45]:
y.value_counts(normalize=True)


3    0.344444
2    0.333333
1    0.322222
Name: Rank, dtype: float64

In [46]:
print('baseline:', y.value_counts(normalize=True).max())


baseline: 0.34444444444444444


### 5. Choose 4 features to be your predictor variables and set up your design matrix.

In [51]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
Xs = scaler.fit_transform(X)




/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/anaconda3/lib/python3.7/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [78]:
Xs.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

### 6. Fit a `KNeighborsClassifier` with 1 neighbor using the target and predictors.

In [52]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(Xs, y)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [53]:
predictions = knn.predict(Xs)
print(np.unique(predictions, return_counts=True))


(array([1, 2, 3]), array([30, 32, 28]))


In [54]:
predictions


array([1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 2, 2,
       1, 1, 1, 1, 1, 2, 1, 3, 1, 1, 2, 1, 2, 1, 2, 2, 3, 2, 1, 1, 1, 2,
       3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 2,
       3, 2, 3, 2, 3, 3, 3, 3, 3, 2, 3, 1, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3,
       3, 3])

In [56]:
probs = knn.predict_proba(Xs)
probs[-10:]
# [0.2, 0.4, 0.4], same prob 0.4, and it's belong to category 2?

array([[0. , 0.4, 0.6],
       [0.2, 0.4, 0.4],
       [0. , 0. , 1. ],
       [0. , 0.2, 0.8],
       [0. , 0.2, 0.8],
       [0. , 0.2, 0.8],
       [0.2, 0.2, 0.6],
       [0. , 0.4, 0.6],
       [0. , 0.2, 0.8],
       [0. , 0. , 1. ]])

In [57]:
probs.shape

(90, 3)

### 7. Evaluate the accuracy of your model.
- Is it better than baseline?
- Is it legitimate?

In [58]:
knn.score(Xs, y)


0.7111111111111111

### 8. Create a 50-50 train-test-split of your target and predictors. Refit the KNN and assess the accuracy.

In [61]:
from sklearn.model_selection import train_test_split, cross_val_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=1)
scaler = StandardScaler()
Xs_1 = scaler.fit_transform(X_train)


/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/anaconda3/lib/python3.7/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [64]:
y_train.value_counts()


1    21
3    15
2     9
Name: Rank, dtype: int64

In [65]:
print('baseline:', y_train.value_counts(normalize=True).max())


baseline: 0.4666666666666667


In [67]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(Xs_1, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [68]:
predictions_1 = knn.predict(Xs_1)
print(np.unique(predictions, return_counts=True))


(array([1, 2, 3]), array([30, 32, 28]))


In [69]:
predictions_1


array([3, 1, 1, 1, 1, 1, 3, 2, 2, 1, 3, 1, 1, 1, 1, 3, 2, 1, 3, 3, 1, 3,
       1, 3, 3, 3, 1, 1, 1, 2, 2, 1, 1, 3, 3, 1, 1, 3, 3, 1, 3, 1, 3, 1,
       2])

In [70]:
probs_1 = knn.predict_proba(Xs_1)
probs_1[-10:]


array([[0.8, 0.2, 0. ],
       [0.6, 0.4, 0. ],
       [0.2, 0. , 0.8],
       [0.2, 0.2, 0.6],
       [0.6, 0.2, 0.2],
       [0. , 0.4, 0.6],
       [0.4, 0.4, 0.2],
       [0. , 0.2, 0.8],
       [1. , 0. , 0. ],
       [0.2, 0.6, 0.2]])

In [71]:
knn.score(Xs_1, y_train)


0.8222222222222222

In [72]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train, predictions_1)


0.8222222222222222

### 9. Evaluate the test accuracy of a KNN where K == number of rows in the training data.

In [73]:
scores = cross_val_score(knn, Xs_1, y_train, cv=5)
print(scores)
print(np.mean(scores))


[0.5        0.77777778 0.55555556 0.77777778 0.75      ]
0.6722222222222223


In [75]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.neighbors import KNeighborsClassifier


In [76]:
skf = StratifiedKFold(n_splits=5) # can also call shuffle function. 
scores = cross_val_score(knn, Xs_1, y_train, cv=skf)
print(scores)
print(np.mean(scores))


[0.5        0.77777778 0.55555556 0.77777778 0.75      ]
0.6722222222222223


### 10. Fit the KNN at values of K from 1 to the number of rows in the training data.
- Store the test accuracy in a list.
- Plot the test accuracy vs. the number of neighbors.

In [13]:
# A:

### 11. Fit KNN across different values of K and plot the mean cross-validated accuracy with 5 folds.

In [14]:
# A:

### 12. Standardize the predictor matrix and cross-validate across the different K.
- Plot the standardized mean cross-validated accuracy against the unstandardized. Which is better?
- Why?

In [15]:
# A: