<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Scipy sparse matrices



[Scipy sparse](https://docs.scipy.org/doc/scipy/reference/sparse.html)

In [1]:
import numpy as np
from scipy import sparse

### Set up a sparse matrix

In [3]:
row = np.array([0, 2, 2, 0, 1, 2])
col = np.array([0, 0, 1, 2, 2, 2])
data = np.array([1, 2, 3, 4, 5, 6])
A = sparse.csr_matrix((data,( row, col)), shape=(3, 3))
A

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

### Print format

In [4]:
print(A)

  (0, 0)	1
  (0, 2)	4
  (1, 2)	5
  (2, 0)	2
  (2, 1)	3
  (2, 2)	6


### Convert to numpy array

### Convert to numpy array

In [4]:
print(A.toarray())

[[1 0 4]
 [0 0 5]
 [2 3 6]]


### Number of nonzero elements

In [5]:
A.nnz

6

### Indices of nonzero elements

In [6]:
A.nonzero()

(array([0, 0, 1, 2, 2, 2], dtype=int32),
 array([0, 2, 2, 0, 1, 2], dtype=int32))

### Usual matrix commands

In [7]:
A.shape

(3, 3)

In [8]:
A.diagonal()

array([1, 0, 6], dtype=int64)

In [9]:
A.sum()

21

In [10]:
print(A.sum(axis=0))
print(A.sum(axis=1))

[[ 3  3 15]]
[[ 5]
 [ 5]
 [11]]


In [11]:
A.dot(A).toarray()

array([[ 9, 12, 28],
       [10, 15, 30],
       [14, 18, 59]], dtype=int64)

### Stacking sparse matrices

In [12]:
print(sparse.hstack([A,A]).toarray())

[[1 0 4 1 0 4]
 [0 0 5 0 0 5]
 [2 3 6 2 3 6]]


In [13]:
print(sparse.vstack([A,A]).toarray())

[[1 0 4]
 [0 0 5]
 [2 3 6]
 [1 0 4]
 [0 0 5]
 [2 3 6]]


### Extracting parts of a sparse matrix

In [14]:
A.getcol(1).toarray()

array([[0],
       [0],
       [3]])

In [15]:
A.getrow(1).toarray()

array([[0, 0, 5]], dtype=int64)

In [16]:
A.argmax()

8