<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Linear algebra practice

---

In [1]:
import numpy as np

#### 1. Transform the following two vectors into numpy arrays.

In [2]:
vec_1 = [2, 4, 1]
vec_2 = [1, 3, 0]

In [3]:
vec_1= np.array([2, 4, 1])
vec_2= np.array([1, 3, 0]) 

#### 2. For the two vectors, calculate
    
- $3 \cdot {\rm vec}_1 + 2\cdot {\rm vec}_2$
- $-0.5\cdot {\rm vec}_1 + 3\cdot {\rm vec}_2$ 
- the scalar product 
- the magnitude of each vector

In [4]:
3*vec_1+2*vec_2

array([ 8, 18,  3])

In [5]:
-0.5*vec_1+3*vec_2

array([ 2. ,  7. , -0.5])

In [6]:
vec_1.dot(vec_2)         # ???the scalar product  就是.dot()

14

In [7]:
np.linalg.norm(vec_1)

4.58257569495584

In [8]:
np.linalg.norm(vec_2)

3.1622776601683795

#### 3. Transform the following lists into numpy matrices.

In [9]:
A = [[2,1],[-2,3]]
B = [[1,3,4],[0,1,2],[1,0,0]]  
C = [[2,3,0],[0,1,4],[1,0,1]]

In [10]:
A= np.array([[2,1],[-2,3]])             #这样就已经是numpy的矩阵了
B= np.array([[1,3,4],[0,1,2],[1,0,0]])
C = np.array([[2,3,0],[0,1,4],[1,0,1]])

In [11]:
A

array([[ 2,  1],
       [-2,  3]])

#### 4. Extract the row and column vectors from A.

In [12]:
A[1,1]

3

#### 5. Form the matrix products $B\cdot C$ and $C\cdot B$. Compare!

In [13]:
B.dot(C)

array([[ 6,  6, 16],
       [ 2,  1,  6],
       [ 2,  3,  0]])

In [14]:
C.dot(B)

array([[ 2,  9, 14],
       [ 4,  1,  2],
       [ 2,  3,  4]])

In [15]:
np.dot(C,B)

array([[ 2,  9, 14],
       [ 4,  1,  2],
       [ 2,  3,  4]])

#### 6. Form the dot products $B\cdot {\rm vec}_1$ and ${\rm vec}_1\cdot B$. Compare!

In [16]:
B.dot(vec_1)    #这点非常重要，在矩阵里面，AB 与 BA 的乘积是不同的！！！

array([18,  6,  2])

In [17]:
vec_1.dot(B)

array([ 3, 10, 16])

#### 7. Obtain the transpose of the matrices $A$, $B$, $C$.

In [18]:
A.T

array([[ 2, -2],
       [ 1,  3]])

In [19]:
B.T

array([[1, 0, 1],
       [3, 1, 0],
       [4, 2, 0]])

In [20]:
C.T

array([[2, 0, 1],
       [3, 1, 0],
       [0, 4, 1]])

#### 8. Form the matrix product $A^T \cdot A$ and $A\cdot A^T$. Compare! Repeat for the matrices $B$ and $C$. Do you notice anything special about the resulting matrices?

In [21]:
A.T.dot(A)        #对角线两遍的数字是对称的

array([[ 8, -4],
       [-4, 10]])

In [22]:
A.dot(A.T)      # 相乘的顺序还是很重要

array([[ 5, -1],
       [-1, 13]])

In [23]:
B.T.dot(B)

array([[ 2,  3,  4],
       [ 3, 10, 14],
       [ 4, 14, 20]])

In [25]:
B.dot(B.T)

array([[26, 11,  1],
       [11,  5,  0],
       [ 1,  0,  1]])

In [26]:
C.T.dot(C)

array([[ 5,  6,  1],
       [ 6, 10,  4],
       [ 1,  4, 17]])

In [27]:
C.dot(C.T)

array([[13,  3,  2],
       [ 3, 17,  4],
       [ 2,  4,  2]])

#### 9. Calculate the inverse matrices of $A$, $B$ and $C$ if possible. Check that the found matrices are indeed the inverses by taking the matrix product with the original matrices.

In [28]:
np.linalg.inv(A)

array([[ 0.375, -0.125],
       [ 0.25 ,  0.25 ]])

In [29]:
np.linalg.inv(B)

array([[ 0.00000000e+00,  2.22044605e-16,  1.00000000e+00],
       [ 1.00000000e+00, -2.00000000e+00, -1.00000000e+00],
       [-5.00000000e-01,  1.50000000e+00,  5.00000000e-01]])

In [30]:
np.linalg.inv(C)

array([[ 0.07142857, -0.21428571,  0.85714286],
       [ 0.28571429,  0.14285714, -0.57142857],
       [-0.07142857,  0.21428571,  0.14285714]])

In [31]:
np.linalg.inv(A).dot(A)

array([[1., 0.],
       [0., 1.]])

In [32]:
np.linalg.inv(B).dot(B)

array([[1.00000000e+00, 2.22044605e-16, 4.44089210e-16],
       [0.00000000e+00, 1.00000000e+00, 4.44089210e-16],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [33]:
np.linalg.inv(C).dot(C)

array([[ 1.00000000e+00, -1.66533454e-16,  1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

#### 10. Solve the system of equations

$$
\begin{eqnarray}
2\, x_1 + 1\, x_2 &=& 3\\
-2\, x_1 + 3\, x_2 &=& 1
\end{eqnarray}$$

Note that this system of equations can be written as

$$
\left(
\begin{array}{cc}
2&1\\
-2&3
\end{array}
\right)
\left(
\begin{array}{c}
x_1\\
x_2 
\end{array}
\right)
=
\left(
\begin{array}{c}
3\\
1 
\end{array}
\right)
$$

Find out how to use the command `np.linalg.solve` to solve this system of equations.

In [38]:
matrix_1= np.array([[2,1],[-2,3]])
matrix_2= np.array([[3],[1]])
result_12=np.linalg.solve(matrix_1,matrix_2)
print(result_12)

[[1.]
 [1.]]


#### 11. Check that the same result can be obtained by calculating

$$
\left(
\begin{array}{cc}
2&1\\
-2&3
\end{array}
\right)^{-1}
\left(
\begin{array}{c}
3\\
1 
\end{array}
\right)
$$

In [39]:
np.linalg.inv(matrix_1).dot(matrix_2)

array([[1.],
       [1.]])

### In the following exercises, work purely with python lists to create your own functions which do the same as the numpy functions. Verify your results with the examples from above.

#### 12. Write a function that adds two vectors to each other

In [50]:
vec_1 = [2, 4, 1]
vec_2 = [1, 3, 0]
A = [[2,1],[-2,3]]
B = [[1,3,4],[0,1,2],[1,0,0]]  
C = [[2,3,0],[0,1,4],[1,0,1]]

In [51]:
def vectors_add(list_1,list_2):
    list_sum=[sum(vec) for vec in zip(list_1,list_2)]
    return(list_sum)
    

In [52]:
vectors_add(vec_1,vec_2)

[3, 7, 1]

In [59]:
def vectors_add_3(list_1,list_2):
    list_sum=[sum(x) for x in vec for vec in zip(list_1,list_2)]
    return(list_sum)

In [60]:
vectors_add_1(B,C)    #not working because the elements in B and C are lists...
# so, how can you unpack them, make them look more like vec_1

NameError: name 'vectors_add_1' is not defined

#### 13. Write a function that subtracts two vectors from each other

In [ ]:
def vectors_sub()

#### 14. Write a function that multiplies a vector by a number

#### 15. Write a function that calculates the length of a vector

#### 16. Write a function that calculates the scalar product of two vectors

#### 17. Write a function that returns the rows of a matrix

#### 18. Write a function that returns the columns of a matrix

#### 19. Write a function that multiplies a matrix with a vector

#### 20. Write a function that multiplies a matrix with a matrix 

#### 21. Write a function that returns the transpose of a given matrix